### PR TITLE
Create the visualisation method for leaf target distribution

### LINKED ISSUE #63: Make leaf split plot for regressors to show distribution of leaf sample y's
I wonder if a split plot per leaf would look ok; seems like it'd be useful, @tlapusan.  Here is a sample split plot.  Maybe one y range / axis on left and then tight grouping of split plots?

Screen Shot 2019-10-28 at 10 44 58 AM

### PR DESCRIPTION
**Pull request by tlapusan**
Create the first version for this visualisation. 
We could add new improvements on this PR if it's needed.

Close #63

### CODE REVIEW

**Comment by parrt** [comment]
From #63,

**Comment by parrt** [comment]
Hmm...here's a thought...what if you displayed the leaf id as y axis not horizontal axis?  Then large trees get taller, not wider graphs and we don't need the splitting of graphs?

**Comment by tlapusan** [comment]
Very nice idea! Will try to implement it

**Comment by parrt** [comment]
Maybe we should do the same for your other leaf visualizations?

**Comment by tlapusan** [comment]
> Maybe we should do the same for your other leaf visualizations?

yes, it could be a valid option. Let's see how it looks for this visualisation and we will decide afterward.

**Comment by parrt** [comment]
can you send a sample pic of horizontal?

**Pull request merged**
