### PR TITLE
Import ABC from collections.abc for Python 3.10 compatibility.

### LINKED ISSUE #128: shadow_decision_tree.py: importing from collections raises a DeprecationWarning in Python 3.9
Hi there!

Running the tests gave the following warning:
```
  /usr/lib/python3/dist-packages/dtreeviz/models/shadow_decision_tree.py:2: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
    from collections import Sequence
```

The solution is to replace this line with:
```python
    from collections.abc import Sequence
```

### PR DESCRIPTION
**Pull request by tirkarthi**
Fixes #128

### CODE REVIEW

**Comment by tlapusan** [comment]
thanks @tirkarthi for this PR. 
I've checked it and also the unit tests are working.

We are using also defaultdict from collections, but it doesn't need this update.

@parrt from my side, it's ok to merge.

**Comment by parrt** [comment]
Are we sure collections.abc works in 3.6? maybe we change to 3.7?

**Comment by tlapusan** [comment]
On my laptop I have python 3.7... Could be an idea to change to python requirement >= 3.7

**Comment by parrt** [comment]
I found a version of 3.6 and this worked `from collections.abc import Sequence`!

**Comment by tirkarthi** [comment]
It should work from 3.4 and above.

**Pull request merged**
