### PR TITLE
Support spark decision tree

### LINKED ISSUE #94: Spark Decision Tree support
Spark community lacks almost entirely model tree interpretation. Would be helpful to add support into dtreeviz.

I've already started to work on it and implemented two visualizations : 
Screen Shot 2020-08-03 at 10 03 13 AM

### PR DESCRIPTION
**Pull request by tlapusan**
Hi @parrt 

I've finished the spark decision tree integration. 

Please take a look over it. Any feedback is welcomed !

Close #94

### CODE REVIEW

**Comment by parrt** [comment]
wow! hooray!  Let me look in more detail tomorrow.  By the way, are the binary files needed like: `/part-00000-65d1fe70-5c43-4fd5-b250-7020b561625a-c000.snappy.parquet`?

**Comment by tlapusan** [comment]
> wow! hooray! Let me look in more detail tomorrow. By the way, are the binary files needed like: `/part-00000-65d1fe70-5c43-4fd5-b250-7020b561625a-c000.snappy.parquet`?

yes, we need them. This is how Spark saves a ML model (so we need both data/ and metadata/ subdirectories for loading the model during testing)

**Comment by parrt** [comment]
Excellent work, as always, @tlapusan !!! great job. merging.

**Comment by parrt** [comment]
@tlapusan bumped to 1.1 in setup.py. added 'pyspark' to requirements. is that a burden? should it leave that and xgboost off as many don't use those?

**Comment by parrt** [comment]
confirmed that notebooks run :)

**Comment by parrt** [comment]
Actually, sklearn fails. must a version issue. i have recently reinstalled anaconda. This is the notebook for sklearn:

Screen Shot 2020-09-01 at 10 21 36 AM

**Comment by tlapusan** [comment]
hi @parrt,

Screen Shot 2020-09-02 at 3 02 57 PM

I've reproduced the 'sk_dtree_balanced.get_prediction_value(4)/...' error, fixed on my local project, I will add the fix with my next commit. That line of code used an old API for get_prediction() method. Tested again all sklearn notebook and it fully works.

"is that a burden" ... do you mean the package size ?

**Comment by parrt** [comment]
"burden":  I'm just wondering if when they install our package it will take much longer to install all these other packages. maybe not. it did not seem to take very long to get spark.

**Comment by tlapusan** [comment]
It didn't take too much time for me also to install dtreeviz... and if the dtreeviz is installed in an environment with sklearn/xgboost/spark already installed, the dependency requirement should be already satisfied.

I don't have a strong preference what to choose... but I will go with specifying all the dependencies in setup.py

**Comment by parrt** [comment]
Let me know when you have the fix for `get_prediction_value` and we can release.

**Comment by tlapusan** [comment]
I've created #98 PR.
It was just a notebook cell effected, no business logic from the library

**Comment by parrt** [comment]
ah. ok, cool. Do you think we're ready for another release? Maybe we should ask that Uber guy again to see if it works with his spark stuff?

**Comment by tlapusan** [comment]
We could make a new release :) The Uber guys, if I'm remember correctly, they use spark with xgboost...which is not implemented by default in spark ml library. Not sure which is the API for Spark with xgboost. 

But for sure we can take again the contact with they.

**Comment by tlapusan** [comment]
hi @parrt, any plans of releasing the spark integration ? :)

**Comment by parrt** [comment]
Oh sorry. distracted. did you hear from the uber dude? It'd be nice to get some outside testing.

**Comment by tlapusan** [comment]
> Oh sorry. distracted. did you hear from the uber dude? It'd be nice to get some outside testing.

I asked him here : https://github.com/parrt/dtreeviz/issues/83

**Pull request merged**
