### PR TITLE
Fix the wierd histogram node display by adding a bin length at the be…

### LINKED ISSUE #196: weird histogram display
Hi again,

After modeling when I draw trees, I always get the histogram of "U" variable as below:

image

It's not clear to interpret and I don't know why it seems like that. I don't think it's due to data. Because, I tried changing the name of this variable or divided the values by 10, but nothing has changed after that.

I am sharing the data and my brief notebook below. So you can read data and run codes in your local and see the issue in trees. As I was saying previously, the weird display happens to the "U" variable only.

```
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
import lightgbm as lgb
from sklearn.metrics import f1_score
import optuna
from dtreeviz.trees import dtreeviz 
from dtreeviz.models.lightgbm_decision_tree import ShadowLightGBMTree
#Supress optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)
import logging
logging.getLogger('matplotlib.font_manager').disabled = True
pd.set_option('display.max_columns', 300)
pd.set_option('display.max_rows', 300)

df_code_tree = pd.read_excel('df_code_tree.xlsx')

# ### Modeling


X_tree=df_code_tree.drop('TARGET', axis=1)
y_tree=df_code_tree.TARGET

#split data into training and test sets
X_train_tree, X_test_tree, y_train_tree, y_test_tree = train_test_split(X_tree, y_tree, test_size = 0.30, random_state=42)

if y_train_tree.value_counts()[0] < 9*y_train_tree.value_counts()[1]:
    pass
else:
    # instantiating over and under sampler
    over = RandomOverSampler(sampling_strategy=0.33)
    under = RandomUnderSampler(sampling_strategy=0.5)
    # first performing oversampling to minority class
    X_train_tree, y_train_tree = over.fit_resample(X_train_tree, y_train_tree)
    # now to combine under sampling 
    X_train_tree, y_train_tree = under.fit_resample(X_train_tree, y_train_tree)

#DT oluştururken 'class_names' ataması yapmak için hedef değişken içeriğini (0,1) olarak bir listede tutuyor ve isimlendiriyoruz.
target = sorted(y_train_tree.unique())

target[0] = "0"
target[1] = "1"

y_train_tree = y_train_tree.astype('int')
y_test_tree = y_test_tree.astype('int')

def objective(trial, train_x, train_y, test_x, test_y):
    dtrain = lgb.Dataset(train_x, label=train_y)
 
    param = {
        "objective":"binary",
        "random_state":42,
        "force_col_wise":True,
        "verbose":-1,
        "n_estimators": trial.suggest_categorical("n_estimators", [10,15,25]),
        "learning_rate": trial.suggest_categorical("learning_rate", [0.003,0.01,0.02,0.15,0.3]),
        "colsample_bytree": trial.suggest_categorical("colsample_bytree", [0.5,0.6,0.8,0.9,1.0]),
        "num_leaves": trial.suggest_int("num_leaves", 8, 64),
        "max_depth": trial.suggest_int("max_depth", 3, 7),
        "min_child_samples": trial.suggest_categorical("min_child_samples", [13,15,19]),
        "reg_alpha": trial.suggest_loguniform("reg_alpha", 1e-3, 10.0),
        "reg_lambda": trial.suggest_loguniform("reg_lambda", 1e-3, 10.0),
        "min_split_gain": trial.suggest_categorical("min_split_gain", [0.0005,0.001,0.0015,0.002])
    }
 
    gbm = lgb.train(param, dtrain)
    preds = gbm.predict(test_x)
    pred_labels = np.rint(preds)
    f1 = f1_score(test_y, pred_labels)
    return f1
 
study = optuna.create_study(sampler=optuna.samplers.RandomSampler(seed=42), direction="maximize", study_name="LGBM Classifier")
func = lambda trial: objective(trial, X_train_tree, y_train_tree, X_test_tree, y_test_tree)
study.optimize(func, n_trials=1000)

#print(f"\tBest value (f1_score): {study.best_value:.5f}")
#print(f"\tBest params:")

#for key, value in study.best_params.items():
 #   print(f"\t\t{key}: {value}")
    
params = study.best_params
params['objective']='binary'
params['random_state']=42
params['verbose']=-1
params['force_col_wise']=True
params['n_jobs']=-1
gbm_dtreeviz = lgb.train(params, lgb.Dataset(X_train_tree, label=y_train_tree))

light_dtree = ShadowLightGBMTree(gbm_dtreeviz, tree_index=0, x_data=X_train_tree, y_data=y_train_tree, feature_names=list(X_tree), target_name="quality_status", class_names=target)
dtreeviz(light_dtree, scale=1.75)
```

[df_code_tree.xlsx](https://github.com/parrt/dtreeviz/files/9653155/df_code_tree.xlsx)

### PR DESCRIPTION
**Pull request by tlapusan**
@parrt I tested this change on multiple dtreeviz visualisations and it works. Give it a try also :)

close #196

### CODE REVIEW

**Comment by parrt** [comment]
Cool. Does it mess up how wide the bars are on any of our examples?

**Comment by tlapusan** [comment]
I didn't observe any difference. Better if you could take a look .

**Comment by parrt** [comment]
Yep. Will check later today

**Comment by parrt** [comment]
looking good.  remind me though...did the bar chart bars look this far apart before?

Screen Shot 2022-11-27 at 2 32 02 PM

**Comment by parrt** [comment]
Ok, yep, looks the same:

**Pull request merged**
