### PR TITLE
Support for tf df trees #181

### PR DESCRIPTION
**Pull request by tlapusan**

### CODE REVIEW

**Comment by parrt** [comment]
Looks like we have merge conflict?

**Comment by tlapusan** [comment]
Fixed it with a new commit.

**Comment by parrt** [comment]
weird. still shows conflict on github.

**Comment by tlapusan** [comment]
indeed weird, I had some conflicts for the initial PR, but I fixed them.
for me the github looks like :
Screenshot 2022-09-26 at 11 55 45

**Comment by parrt** [comment]
Weird!!!

Screen Shot 2022-09-26 at 10 44 40 AM

**Comment by parrt** [comment]
hmm...manual merge worked no conflict!!

**Pull request merged**
